import Head from "next/head";
import { useState } from "react";
import LoadHome from "./components/home.js";
import LoadMarket from "./components/marketplace.js";
import LoadAbout from "./components/about.js";
import styles from "../css_components/navBar.module.css";

export default function Home() {

  const [tab,setTab] = useState("home");

  const LoadTab = () => {
    switch (tab){
      case "home":
        return <LoadHome />
      case "market":
        return <LoadMarket />
      case "about":
        return <LoadAbout />
    }

  }
  

  return (
    <>
      <Head>
        <title>Lucruri Furate Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <div className={styles.title}>
          <strong>Buy Cheap!!!</strong>
        </div>
        <div className={styles.navBar}>
            <button onClick={() => setTab("home")} className={styles.navBarBTN}>Main Page</button>
            <button onClick={() => setTab("market")} className={styles.navBarBTN}> The Marketplace</button>
            <button onClick={() => setTab("about")} className={styles.navBarBTN}>Contact me</button>
        </div>
      </div>
      <LoadTab />
    </>
  );
}
